package com.bgs.boardgameshop.config;

import com.bgs.boardgameshop.game.Game;
import com.bgs.boardgameshop.game.GameRepository;
import com.bgs.boardgameshop.game.Tag;
import com.bgs.boardgameshop.game.TagRepository;
import com.bgs.boardgameshop.order.Order;
import com.bgs.boardgameshop.order.OrderLine;
import com.bgs.boardgameshop.order.OrderRepository;
import com.bgs.boardgameshop.order.OrderStatus;
import com.bgs.boardgameshop.review.Review;
import com.bgs.boardgameshop.review.ReviewRepository;
import com.bgs.boardgameshop.user.Role;
import com.bgs.boardgameshop.user.User;
import com.bgs.boardgameshop.user.UserRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Peuple le catalogue, quelques tags et comptes de démonstration au démarrage,
 * pour avoir des données prêtes à l'emploi (base vide uniquement, voir seedUsers/seedGames).
 */
@Component
public class DataSeeder implements CommandLineRunner {

    private final GameRepository gameRepository;
    private final TagRepository tagRepository;
    private final UserRepository userRepository;
    private final OrderRepository orderRepository;
    private final ReviewRepository reviewRepository;
    private final PasswordEncoder passwordEncoder;

    public DataSeeder(
            GameRepository gameRepository,
            TagRepository tagRepository,
            UserRepository userRepository,
            OrderRepository orderRepository,
            ReviewRepository reviewRepository,
            PasswordEncoder passwordEncoder
    ) {
        this.gameRepository = gameRepository;
        this.tagRepository = tagRepository;
        this.userRepository = userRepository;
        this.orderRepository = orderRepository;
        this.reviewRepository = reviewRepository;
        this.passwordEncoder = passwordEncoder;
    }

    @Override
    public void run(String... args) {
        seedUsers();
        Map<String, Tag> tags = seedTags();
        seedGames(tags);
        linkExpansions();
        seedOrderAndReviews();
    }

    private void seedUsers() {
        if (userRepository.count() > 0) {
            return;
        }

        userRepository.saveAll(List.of(
                User.builder()
                        .email("admin@bgs.fr")
                        .passwordHash(passwordEncoder.encode("admin1234"))
                        .firstName("Admin")
                        .lastName("BGS")
                        .role(Role.ADMIN)
                        .createdAt(Instant.now())
                        .build(),
                User.builder()
                        .email("user@bgs.fr")
                        .passwordHash(passwordEncoder.encode("user1234"))
                        .firstName("Jean")
                        .lastName("Dupont")
                        .role(Role.USER)
                        .createdAt(Instant.now())
                        .build()
        ));
    }

    private Map<String, Tag> seedTags() {
        if (tagRepository.count() > 0) {
            return tagRepository.findAll().stream()
                    .collect(Collectors.toMap(Tag::getName, t -> t));
        }

        List<Tag> tags = List.of(
                Tag.builder().name("Coopératif").slug("cooperatif").build(),
                Tag.builder().name("Gestion de ressources").slug("gestion-de-ressources").build(),
                Tag.builder().name("Deck-building").slug("deck-building").build(),
                Tag.builder().name("Draft").slug("draft").build(),
                Tag.builder().name("Bluff").slug("bluff").build(),
                Tag.builder().name("Énigme").slug("enigme").build(),
                Tag.builder().name("Pose de tuiles").slug("pose-de-tuiles").build(),
                Tag.builder().name("Ambiance familiale").slug("ambiance-familiale").build(),
                Tag.builder().name("Placement d'ouvriers").slug("placement-douvriers").build(),
                Tag.builder().name("Combat").slug("combat").build(),
                Tag.builder().name("Science-fiction").slug("science-fiction").build(),
                Tag.builder().name("Civilisation").slug("civilisation").build(),
                Tag.builder().name("Économie").slug("economie").build(),
                Tag.builder().name("Abstrait").slug("abstrait").build(),
                Tag.builder().name("Cartes").slug("cartes").build(),
                Tag.builder().name("Dés").slug("des").build(),
                Tag.builder().name("Exploration").slug("exploration").build(),
                Tag.builder().name("Campagne").slug("campagne").build(),
                Tag.builder().name("Fantasy").slug("fantasy").build(),
                Tag.builder().name("Enchères").slug("encheres").build()
        );

        return tagRepository.saveAll(tags).stream().collect(Collectors.toMap(Tag::getName, t -> t));
    }

    private void seedGames(Map<String, Tag> tags) {
        if (gameRepository.count() > 0) {
            return;
        }

        LocalDate today = LocalDate.now();

        gameRepository.saveAll(List.of(
                Game.builder()
                        .name("Catane")
                        .description("Colonisez une île, échangez des ressources et bâtissez routes et cités.")
                        .price(new BigDecimal("34.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/0XODRpReiZBFUffEcqT5-Q__itemrep/img/6Jf5G-bSvdOIMUSwxsJfZXl29B8=/fit-in/246x300/filters:strip_icc()/pic9156909.png")
                        .publisher("Kosmos")
                        .minPlayers(3).maxPlayers(4).durationMinutes(90)
                        .stock(25)
                        .minAge(10)
                        .releaseDate(today.minusYears(5))
                        .tags(Set.of(tags.get("Gestion de ressources")))
                        .build(),
                Game.builder()
                        .name("Carcassonne")
                        .description("Construisez cités, routes et abbayes en posant des tuiles au fil de la partie.")
                        .price(new BigDecimal("24.90"))
                        .category("Famille")
                        .imageUrl("https://cf.geekdo-images.com/peUgu3A20LRmAXAMyDQfpQ__itemrep/img/6TWoEvnQQe_sO--6WLd_PQOnEQg=/fit-in/246x300/filters:strip_icc()/pic8621446.jpg")
                        .publisher("Hans im Glück")
                        .minPlayers(2).maxPlayers(5).durationMinutes(45)
                        .stock(30)
                        .minAge(7)
                        .releaseDate(today.minusYears(8))
                        .discountPercent(15)
                        .discountEndsAt(Instant.now().plus(14, ChronoUnit.DAYS))
                        .tags(Set.of(tags.get("Pose de tuiles"), tags.get("Ambiance familiale")))
                        .build(),
                Game.builder()
                        .name("7 Wonders")
                        .description("Développez une civilisation antique à travers trois âges, en draft de cartes.")
                        .price(new BigDecimal("39.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/35h9Za_JvMMMtx_92kT0Jg__itemrep/img/EUlr4of74-i75S-jIrgNfaQ3M6Q=/fit-in/246x300/filters:strip_icc()/pic7149798.jpg")
                        .publisher("Repos Production")
                        .minPlayers(3).maxPlayers(7).durationMinutes(30)
                        .stock(18)
                        .minAge(10)
                        .releaseDate(today.minusYears(6))
                        .tags(Set.of(tags.get("Draft")))
                        .build(),
                Game.builder()
                        .name("Terraforming Mars")
                        .description("Dirigez une corporation chargée de rendre Mars habitable.")
                        .price(new BigDecimal("54.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/wg9oOLcsKvDesSUdZQ4rxw__itemrep/img/IwUOQfhP5c0KcRJBY4X_hi3LpsY=/fit-in/246x300/filters:strip_icc()/pic3536616.jpg")
                        .publisher("FryxGames")
                        .minPlayers(1).maxPlayers(5).durationMinutes(120)
                        .stock(12)
                        .minAge(12)
                        .releaseDate(today.minusYears(4))
                        .tags(Set.of(tags.get("Gestion de ressources")))
                        .build(),
                Game.builder()
                        .name("Azul")
                        .description("Composez les plus beaux motifs d'azulejos en piochant des tuiles colorées.")
                        .price(new BigDecimal("29.90"))
                        .category("Ambiance")
                        .imageUrl("https://cf.geekdo-images.com/aPSHJO0d0XOpQR5X-wJonw__itemrep/img/6oRLPDvy4zz3gOZM6e6NzIk8Seg=/fit-in/246x300/filters:strip_icc()/pic6973671.png")
                        .publisher("Plan B Games")
                        .minPlayers(2).maxPlayers(4).durationMinutes(40)
                        .stock(22)
                        .minAge(8)
                        .releaseDate(today.minusYears(3))
                        .tags(Set.of(tags.get("Pose de tuiles")))
                        .build(),
                Game.builder()
                        .name("Dixit")
                        .description("Racontez une histoire à partir d'une carte illustrée et faites deviner les autres.")
                        .price(new BigDecimal("27.90"))
                        .category("Ambiance")
                        .imageUrl("https://cf.geekdo-images.com/J0PlHArkZDJ57H-brXW2Fw__itemrep/img/tsmN3sAHJ6trDaWNbq08BZXtq7g=/fit-in/246x300/filters:strip_icc()/pic6738336.jpg")
                        .publisher("Libellud")
                        .minPlayers(3).maxPlayers(6).durationMinutes(30)
                        .stock(20)
                        .minAge(6)
                        .releaseDate(today.minusYears(10))
                        .tags(Set.of(tags.get("Ambiance familiale")))
                        .build(),
                Game.builder()
                        .name("Pandemic")
                        .description("Unissez vos forces pour enrayer quatre épidémies mondiales avant qu'il ne soit trop tard.")
                        .price(new BigDecimal("32.90"))
                        .category("Coopératif")
                        .imageUrl("https://cf.geekdo-images.com/S3ybV1LAp-8SnHIXLLjVqA__itemrep/img/wAMLbgihOl7dJDHnvqt7OXKEV-4=/fit-in/246x300/filters:strip_icc()/pic1534148.jpg")
                        .publisher("Z-Man Games")
                        .minPlayers(2).maxPlayers(4).durationMinutes(45)
                        .stock(15)
                        .minAge(10)
                        .releaseDate(today.minusYears(9))
                        .discountPercent(20)
                        .discountEndsAt(Instant.now().plus(7, ChronoUnit.DAYS))
                        .tags(Set.of(tags.get("Coopératif")))
                        .build(),
                Game.builder()
                        .name("Splendor")
                        .description("Bâtissez un empire de marchand de pierres précieuses de la Renaissance.")
                        .price(new BigDecimal("26.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/vNFe4JkhKAERzi4T0Ntwpw__itemrep/img/OoBoVLPl4ZYiNioNIKlV_0HLEYQ=/fit-in/246x300/filters:strip_icc()/pic8234167.png")
                        .publisher("Space Cowboys")
                        .minPlayers(2).maxPlayers(4).durationMinutes(30)
                        .stock(28)
                        .minAge(8)
                        .releaseDate(today.minusYears(7))
                        .tags(Set.of(tags.get("Gestion de ressources")))
                        .build(),
                Game.builder()
                        .name("Codenames")
                        .description("Faites deviner les mots de votre équipe en un seul indice, sans toucher à ceux de l'adversaire.")
                        .price(new BigDecimal("19.90"))
                        .category("Party Game")
                        .imageUrl("https://cf.geekdo-images.com/nC6ifPCDnAItwoKSKXVrnw__itemrep/img/iM9m6bb1zTCzDzkXhiKE5V1gomc=/fit-in/246x300/filters:strip_icc()/pic8907965.jpg")
                        .publisher("Czech Games Edition")
                        .minPlayers(2).maxPlayers(8).durationMinutes(15)
                        .stock(35)
                        .minAge(14)
                        .releaseDate(today.minusYears(6))
                        .tags(Set.of(tags.get("Bluff")))
                        .build(),
                Game.builder()
                        .name("Wingspan")
                        .description("Attirez les plus beaux oiseaux dans vos réserves naturelles.")
                        .price(new BigDecimal("44.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/yLZJCVLlIx4c7eJEWUNJ7w__itemrep/img/DR7181wU4sHT6gn6Q1XccpPxNHg=/fit-in/246x300/filters:strip_icc()/pic4458123.jpg")
                        .publisher("Stonemaier Games")
                        .minPlayers(1).maxPlayers(5).durationMinutes(70)
                        .stock(10)
                        .minAge(10)
                        .releaseDate(today.minusYears(2))
                        .tags(Set.of(tags.get("Gestion de ressources"), tags.get("Deck-building")))
                        .build(),
                Game.builder()
                        .name("Nemesis")
                        .description("Survivez à bord d'un vaisseau infesté de créatures hostiles. Précommande ouverte.")
                        .price(new BigDecimal("89.90"))
                        .category("Coopératif")
                        .imageUrl("https://cf.geekdo-images.com/4KSmlm59w0GwLIlgDnJDAQ__itemrep/img/7vNS5kbVuRI8SrRF2L7wOkoMvEQ=/fit-in/246x300/filters:strip_icc()/pic8211747.png")
                        .publisher("Awaken Realms")
                        .minPlayers(1).maxPlayers(5).durationMinutes(120)
                        .stock(8)
                        .minAge(16)
                        .releaseDate(today.plusMonths(2))
                        .tags(Set.of(tags.get("Coopératif"), tags.get("Bluff")))
                        .build(),
                Game.builder()
                        .name("Cascadia")
                        .description("Aménagez un paysage naturel harmonieux pour attirer une faune variée. Sortie à venir.")
                        .price(new BigDecimal("36.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/MjeJZfulbsM1DSV3DrGJYA__itemrep/img/RjD03wEf_LoX0EF4DhnW6f0xNHU=/fit-in/246x300/filters:strip_icc()/pic5100691.jpg")
                        .publisher("Flatout Games")
                        .minPlayers(1).maxPlayers(4).durationMinutes(45)
                        .stock(0)
                        .minAge(10)
                        .releaseDate(today.plusMonths(1))
                        .tags(Set.of(tags.get("Pose de tuiles")))
                        .build(),
                Game.builder()
                        .name("Brass: Birmingham")
                        .description("Développez votre industrie dans les Midlands anglais, du charbon aux réseaux ferrés, sur deux ères historiques.")
                        .price(new BigDecimal("55.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/x3zxjr-Vw5iU4yDPg70Jgw__itemrep/img/giNUMut4HAl-zWyQkGG0YchmuLI=/fit-in/246x300/filters:strip_icc()/pic3490053.jpg")
                        .publisher("Roxley")
                        .minPlayers(2).maxPlayers(4).durationMinutes(120)
                        .stock(10)
                        .minAge(14)
                        .releaseDate(today.minusYears(8))
                        .tags(Set.of(tags.get("Gestion de ressources")))
                        .build(),
                Game.builder()
                        .name("Ark Nova")
                        .description("Concevez et développez un zoo moderne tourné vers la conservation des espèces menacées.")
                        .price(new BigDecimal("59.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/SoU8p28Sk1s8MSvoM4N8pQ__itemrep/img/IRqrT7kOqPQilogauyQkOnLx-HU=/fit-in/246x300/filters:strip_icc()/pic6293412.jpg")
                        .publisher("Feuerland Spiele")
                        .minPlayers(1).maxPlayers(4).durationMinutes(150)
                        .stock(11)
                        .minAge(14)
                        .releaseDate(today.minusYears(5))
                        .tags(Set.of(tags.get("Gestion de ressources")))
                        .build(),
                Game.builder()
                        .name("Gloomhaven")
                        .description("Menez une bande de mercenaires à travers une campagne tactique de donjons dans un monde persistant.")
                        .price(new BigDecimal("139.90"))
                        .category("Aventure")
                        .imageUrl("https://cf.geekdo-images.com/sZYp_3BTDGjh2unaZfZmuA__itemrep/img/0IdBRA_G-ZdrNaxI4Z1LPQMZD0I=/fit-in/246x300/filters:strip_icc()/pic2437871.jpg")
                        .publisher("Cephalofair Games")
                        .minPlayers(1).maxPlayers(4).durationMinutes(120)
                        .stock(12)
                        .minAge(14)
                        .releaseDate(today.minusYears(9))
                        .tags(Set.of(tags.get("Combat"), tags.get("Campagne")))
                        .build(),
                Game.builder()
                        .name("Dune: Imperium")
                        .description("Combinez deck-building et placement d'ouvriers pour dominer la planète Arrakis et ses factions rivales.")
                        .price(new BigDecimal("54.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/PhjygpWSo-0labGrPBMyyg__itemrep/img/3_xJ0tO5L62bUp2oRfjeVS0DHX0=/fit-in/246x300/filters:strip_icc()/pic5666597.jpg")
                        .publisher("Dire Wolf")
                        .minPlayers(1).maxPlayers(4).durationMinutes(120)
                        .stock(13)
                        .minAge(14)
                        .releaseDate(today.minusYears(6))
                        .discountPercent(15)
                        .discountEndsAt(Instant.now().plus(14, ChronoUnit.DAYS))
                        .tags(Set.of(tags.get("Deck-building"), tags.get("Science-fiction")))
                        .build(),
                Game.builder()
                        .name("Twilight Imperium: Fourth Edition")
                        .description("Bâtissez un empire galactique par la diplomatie, le commerce et la guerre, dans l'épopée spatiale ultime.")
                        .price(new BigDecimal("149.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/_Ppn5lssO5OaildSE-FgFA__itemrep/img/rJfEVG0xStfVWbevNWfHBo4ZVrQ=/fit-in/246x300/filters:strip_icc()/pic3727516.jpg")
                        .publisher("Fantasy Flight Games")
                        .minPlayers(3).maxPlayers(6).durationMinutes(480)
                        .stock(14)
                        .minAge(14)
                        .releaseDate(today.minusYears(9))
                        .tags(Set.of(tags.get("Science-fiction")))
                        .build(),
                Game.builder()
                        .name("War of the Ring: Second Edition")
                        .description("Revivez la guerre de l'Anneau : la Communauté tente d'atteindre le Mordor pendant que Sauron mobilise ses armees.")
                        .price(new BigDecimal("89.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/ImPgGag98W6gpV1KV812aA__itemrep/img/dagUJ0H2LGVIjYaeQ_XVweBZRfI=/fit-in/246x300/filters:strip_icc()/pic1215633.jpg")
                        .publisher("Ares Games")
                        .minPlayers(2).maxPlayers(4).durationMinutes(180)
                        .stock(15)
                        .minAge(13)
                        .releaseDate(today.minusYears(15))
                        .tags(Set.of(tags.get("Combat"), tags.get("Fantasy")))
                        .build(),
                Game.builder()
                        .name("Star Wars: Rebellion")
                        .description("L'Empire traque la base rebelle secrète tandis que l'Alliance tente de renverser l'Empereur, dans toute la galaxie.")
                        .price(new BigDecimal("89.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/7SrPNGBKg9IIsP4UQpOi8g__itemrep/img/p6KKXu7b7J6METCTYTIx4tKNqAA=/fit-in/246x300/filters:strip_icc()/pic4325841.jpg")
                        .publisher("Fantasy Flight Games")
                        .minPlayers(2).maxPlayers(4).durationMinutes(240)
                        .stock(16)
                        .minAge(14)
                        .releaseDate(today.minusYears(10))
                        .tags(Set.of(tags.get("Science-fiction")))
                        .build(),
                Game.builder()
                        .name("Spirit Island")
                        .description("Incarnez des esprits protecteurs d'une île et repoussez les colons envahisseurs avant qu'ils ne la devastent.")
                        .price(new BigDecimal("64.90"))
                        .category("Coopératif")
                        .imageUrl("https://cf.geekdo-images.com/kjCm4ZvPjIZxS-mYgSPy1g__itemrep/img/7AXozbOIxk5MDpn_RNlat4omAcc=/fit-in/246x300/filters:strip_icc()/pic7013651.jpg")
                        .publisher("Greater Than Games")
                        .minPlayers(1).maxPlayers(4).durationMinutes(120)
                        .stock(17)
                        .minAge(13)
                        .releaseDate(today.minusYears(9))
                        .tags(Set.of(tags.get("Coopératif")))
                        .build(),
                Game.builder()
                        .name("Gloomhaven: Jaws of the Lion")
                        .description("Point d'entrée autonome dans l'univers de Gloomhaven, avec quatre nouveaux personnages et une campagne resserrée.")
                        .price(new BigDecimal("44.90"))
                        .category("Aventure")
                        .imageUrl("https://cf.geekdo-images.com/_HhIdavYW-hid20Iq3hhmg__itemrep/img/a4ec0KY1ksmrKP_2lom7qzCQw_U=/fit-in/246x300/filters:strip_icc()/pic5055631.jpg")
                        .publisher("Cephalofair Games")
                        .minPlayers(1).maxPlayers(4).durationMinutes(60)
                        .stock(18)
                        .minAge(14)
                        .releaseDate(today.minusYears(6))
                        .tags(Set.of(tags.get("Combat"), tags.get("Campagne")))
                        .build(),
                Game.builder()
                        .name("Gaia Project")
                        .description("Terraformez des planetes et développez une civilisation spatiale parmi quatorze factions asymétriques.")
                        .price(new BigDecimal("69.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/hGWFm3hbMlCDsfCsauOQ4g__itemrep/img/MNyaVUlEsVQmbv3nObPl0SEd_TI=/fit-in/246x300/filters:strip_icc()/pic5375625.png")
                        .publisher("Feuerland Spiele")
                        .minPlayers(1).maxPlayers(4).durationMinutes(150)
                        .stock(19)
                        .minAge(12)
                        .releaseDate(today.minusYears(9))
                        .tags(Set.of(tags.get("Science-fiction"), tags.get("Gestion de ressources")))
                        .build(),
                Game.builder()
                        .name("SETI: Search for Extraterrestrial Intelligence")
                        .description("Explorez le systeme solaire et analysez des signaux pour etre le premier à contacter une intelligence extraterrestre.")
                        .price(new BigDecimal("54.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/_BUXOVRDU9g_eRwgpR5ZZw__itemrep/img/akn-Silkr3votqHnRyacw5b1YsM=/fit-in/246x300/filters:strip_icc()/pic8160466.jpg")
                        .publisher("Awaken Realms")
                        .minPlayers(1).maxPlayers(4).durationMinutes(140)
                        .stock(20)
                        .minAge(14)
                        .releaseDate(today.minusYears(2))
                        .tags(Set.of(tags.get("Science-fiction")))
                        .build(),
                Game.builder()
                        .name("Slay the Spire: The Board Game")
                        .description("Grimpez la Spire en combattant des monstres et en construisant votre deck, adapté du jeu vidéo culte.")
                        .price(new BigDecimal("54.90"))
                        .category("Aventure")
                        .imageUrl("https://cf.geekdo-images.com/PQzVclEoOQ_wr4e1V86kxA__itemrep/img/RTxgAjHxipD5sVBYxisz2V1AruA=/fit-in/246x300/filters:strip_icc()/pic8157856.png")
                        .publisher("Contention Games")
                        .minPlayers(1).maxPlayers(4).durationMinutes(90)
                        .stock(21)
                        .minAge(14)
                        .releaseDate(today.minusYears(2))
                        .tags(Set.of(tags.get("Deck-building"), tags.get("Combat")))
                        .build(),
                Game.builder()
                        .name("Twilight Struggle")
                        .description("Duel entre États-Unis et URSS pour l'influence mondiale, de 1945 à 1989.")
                        .price(new BigDecimal("44.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/pNCiUUphnoeWOYfsWq0kng__itemrep/img/WMsXl-Wa8q2n9_lJH536Mhi2COc=/fit-in/246x300/filters:strip_icc()/pic3530661.jpg")
                        .publisher("GMT Games")
                        .minPlayers(2).maxPlayers(2).durationMinutes(180)
                        .stock(22)
                        .minAge(13)
                        .releaseDate(today.minusYears(21))
                        .discountPercent(20)
                        .discountEndsAt(Instant.now().plus(10, ChronoUnit.DAYS))
                        .build(),
                Game.builder()
                        .name("The Castles of Burgundy")
                        .description("Développez votre principauté bourguignonne en placant tuiles et en gérant vos ressources au fil des lancers de dés.")
                        .price(new BigDecimal("39.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/sH2YTQ10dHj1ibfS-KKtGA__itemrep/img/NN62C1zjDkShyV1ZnkwrOcV907Q=/fit-in/246x300/filters:strip_icc()/pic8745814.jpg")
                        .publisher("Ravensburger")
                        .minPlayers(1).maxPlayers(4).durationMinutes(90)
                        .stock(23)
                        .minAge(12)
                        .releaseDate(today.minusYears(15))
                        .tags(Set.of(tags.get("Dés"), tags.get("Pose de tuiles")))
                        .build(),
                Game.builder()
                        .name("Through the Ages: A New Story of Civilization")
                        .description("Guidez une civilisation de l'Antiquité à l'ère moderne, entre science, culture et puissance militaire.")
                        .price(new BigDecimal("49.90"))
                        .category("Stratégie")
                        .imageUrl("undefined")
                        .publisher("Czech Games Edition")
                        .minPlayers(2).maxPlayers(4).durationMinutes(240)
                        .stock(24)
                        .minAge(14)
                        .releaseDate(today.minusYears(11))
                        .tags(Set.of(tags.get("Civilisation")))
                        .build(),
                Game.builder()
                        .name("The Lord of the Rings: Duel for Middle-earth")
                        .description("Duel de deck-building en équipe entre les forces du Bien et du Mal, sur les terres de la Terre du Milieu.")
                        .price(new BigDecimal("34.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/EybxJlUc9rz7F7HVFLqsdw__itemrep/img/vJcpjMKzCOlOL0R7ywzgPHA2sk8=/fit-in/246x300/filters:strip_icc()/pic8378939.jpg")
                        .publisher("Fantasy Flight Games")
                        .minPlayers(2).maxPlayers(2).durationMinutes(60)
                        .stock(25)
                        .minAge(14)
                        .releaseDate(today.minusYears(2))
                        .tags(Set.of(tags.get("Deck-building"), tags.get("Fantasy")))
                        .build(),
                Game.builder()
                        .name("Frosthaven")
                        .description("Suite de Gloomhaven dans un avant-poste hivernal isolé, avec une campagne tactique encore plus riche.")
                        .price(new BigDecimal("159.90"))
                        .category("Aventure")
                        .imageUrl("https://cf.geekdo-images.com/cwUgf-f-qwri8UHBUnifuQ__itemrep/img/jdzPjZRC5J0C_NL7mhr-4VPdm0I=/fit-in/246x300/filters:strip_icc()/pic5092291.png")
                        .publisher("Cephalofair Games")
                        .minPlayers(1).maxPlayers(4).durationMinutes(120)
                        .stock(26)
                        .minAge(14)
                        .releaseDate(today.minusYears(4))
                        .tags(Set.of(tags.get("Combat"), tags.get("Campagne")))
                        .build(),
                Game.builder()
                        .name("Great Western Trail")
                        .description("Menez vos troupeaux de bétail du Texas à Kansas City en développant votre ranch et vos routes commerciales.")
                        .price(new BigDecimal("54.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/u1l0gH7sb_vnvDvoO_QHqA__itemrep/img/s3qAGoXVCK6gA8nsHDICfZ4Jc1c=/fit-in/246x300/filters:strip_icc()/pic4887376.jpg")
                        .publisher("Eggertspiele")
                        .minPlayers(2).maxPlayers(4).durationMinutes(150)
                        .stock(27)
                        .minAge(12)
                        .releaseDate(today.minusYears(10))
                        .tags(Set.of(tags.get("Gestion de ressources")))
                        .build(),
                Game.builder()
                        .name("Brass: Lancashire")
                        .description("Développez l'industrie du coton dans le Lancashire du 18e siècle, entre canaux et chemins de fer.")
                        .price(new BigDecimal("49.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/tHVtPzu82mBpeQbbZkV6EA__itemrep/img/A9DQBjrHvs1YlYCWMD0mtp-jnNc=/fit-in/246x300/filters:strip_icc()/pic3469216.jpg")
                        .publisher("Roxley")
                        .minPlayers(2).maxPlayers(4).durationMinutes(120)
                        .stock(28)
                        .minAge(14)
                        .releaseDate(today.minusYears(19))
                        .tags(Set.of(tags.get("Gestion de ressources")))
                        .build(),
                Game.builder()
                        .name("Eclipse: Second Dawn for the Galaxy")
                        .description("Explorez, développez et défendez votre empire galactique face à des civilisations rivales et des monstres anciens.")
                        .price(new BigDecimal("89.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/Oh3kHw6lweg6ru71Q16h2Q__itemrep/img/1flTGokf8uwox72PWvkNq3kOhMM=/fit-in/246x300/filters:strip_icc()/pic5235277.jpg")
                        .publisher("Lautapelit.fi")
                        .minPlayers(2).maxPlayers(6).durationMinutes(240)
                        .stock(29)
                        .minAge(14)
                        .releaseDate(today.minusYears(6))
                        .tags(Set.of(tags.get("Science-fiction")))
                        .build(),
                Game.builder()
                        .name("Scythe")
                        .description("Dans une Europe de l'Est uchronique d'après-guerre, développez votre territoire à l'aide de mechs et de fermiers.")
                        .price(new BigDecimal("69.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/7k_nOxpO9OGIjhLq2BUZdA__itemrep/img/RVh5N-_HcMziJ3M6Q1eLTlj8XIQ=/fit-in/246x300/filters:strip_icc()/pic3163924.jpg")
                        .publisher("Stonemaier Games")
                        .minPlayers(1).maxPlayers(5).durationMinutes(115)
                        .stock(10)
                        .minAge(14)
                        .releaseDate(today.minusYears(10))
                        .tags(Set.of(tags.get("Gestion de ressources")))
                        .build(),
                Game.builder()
                        .name("A Feast for Odin")
                        .description("Menez un clan viking à travers raids, exploration et agriculture pour batir la plus prospère des colonies.")
                        .price(new BigDecimal("64.90"))
                        .category("Stratégie")
                        .imageUrl("undefined")
                        .publisher("Feuerland Spiele")
                        .minPlayers(1).maxPlayers(4).durationMinutes(120)
                        .stock(11)
                        .minAge(12)
                        .releaseDate(today.minusYears(10))
                        .discountPercent(10)
                        .discountEndsAt(Instant.now().plus(21, ChronoUnit.DAYS))
                        .tags(Set.of(tags.get("Placement d'ouvriers")))
                        .build(),
                Game.builder()
                        .name("Concordia")
                        .description("Développez un réseau commercial à travers l'Empire romain grâce à une mécanique de cartes originale.")
                        .price(new BigDecimal("39.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/CzwSm8i7tkLz6cBnrILZBg__itemrep/img/kYm-P2lvyVstKDjvEDciaV3XObg=/fit-in/246x300/filters:strip_icc()/pic3453267.jpg")
                        .publisher("PD-Verlag")
                        .minPlayers(2).maxPlayers(5).durationMinutes(100)
                        .stock(12)
                        .minAge(13)
                        .releaseDate(today.minusYears(13))
                        .tags(Set.of(tags.get("Gestion de ressources")))
                        .build(),
                Game.builder()
                        .name("Lost Ruins of Arnak")
                        .description("Explorez une île mystérieuse, combinez deck-building et placement d'ouvriers pour percer ses secrets.")
                        .price(new BigDecimal("44.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/6GqH14TJJhza86BX5HCLEQ__itemrep/img/ETni1QwddAVjM-xLhciF0UM0FxQ=/fit-in/246x300/filters:strip_icc()/pic5674958.jpg")
                        .publisher("Czech Games Edition")
                        .minPlayers(1).maxPlayers(4).durationMinutes(120)
                        .stock(13)
                        .minAge(12)
                        .releaseDate(today.minusYears(6))
                        .tags(Set.of(tags.get("Deck-building"), tags.get("Exploration")))
                        .build(),
                Game.builder()
                        .name("Sky Team")
                        .description("En duo silencieux, coopérez pour faire atterrir votre avion en toute sécurité, en lançant vos dés en secret.")
                        .price(new BigDecimal("24.90"))
                        .category("Coopératif")
                        .imageUrl("https://cf.geekdo-images.com/uXMeQzNenHb3zK7Hoa6b2w__itemrep/img/oaw-LYEIaB20e79Y568JgyHZ5NQ=/fit-in/246x300/filters:strip_icc()/pic7398904.jpg")
                        .publisher("Le Scorpion Masque")
                        .minPlayers(2).maxPlayers(2).durationMinutes(20)
                        .stock(14)
                        .minAge(12)
                        .releaseDate(today.minusYears(3))
                        .tags(Set.of(tags.get("Coopératif"), tags.get("Dés")))
                        .build(),
                Game.builder()
                        .name("Root")
                        .description("Guerre de territoire asymétrique dans une forêt peuplée d'animaux, entre empire féodal, rebelles et vagabond.")
                        .price(new BigDecimal("49.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/JUAUWaVUzeBgzirhZNmHHw__itemrep/img/sQgkl-_hydBVvQHAMLt2Zk_3dwI=/fit-in/246x300/filters:strip_icc()/pic4254509.jpg")
                        .publisher("Leder Games")
                        .minPlayers(2).maxPlayers(4).durationMinutes(90)
                        .stock(15)
                        .minAge(10)
                        .releaseDate(today.minusYears(8))
                        .tags(Set.of(tags.get("Combat")))
                        .build(),
                Game.builder()
                        .name("Orleans")
                        .description("Recrutez des habitants dans un sac et gérez leur influence pour prospérer dans la France médiévale.")
                        .price(new BigDecimal("44.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/nagl1li6kYt9elV9jbfVQw__itemrep/img/oYYWKekDiHllrWnFNef7En3gP4c=/fit-in/246x300/filters:strip_icc()/pic6228507.jpg")
                        .publisher("dlp games")
                        .minPlayers(2).maxPlayers(4).durationMinutes(120)
                        .stock(16)
                        .minAge(12)
                        .releaseDate(today.minusYears(12))
                        .tags(Set.of(tags.get("Deck-building")))
                        .build(),
                Game.builder()
                        .name("Terra Mystica")
                        .description("Quatorze peuples fantastiques s'affrontent pour transformer le terrain et étendre leur civilisation.")
                        .price(new BigDecimal("64.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/bre12I1YiXkZr7elvriz4A__itemrep/img/pKM9lklmQLXJx2xta9eR5NSezec=/fit-in/246x300/filters:strip_icc()/pic5375624.jpg")
                        .publisher("Feuerland Spiele")
                        .minPlayers(2).maxPlayers(5).durationMinutes(150)
                        .stock(17)
                        .minAge(12)
                        .releaseDate(today.minusYears(14))
                        .tags(Set.of(tags.get("Civilisation")))
                        .build(),
                Game.builder()
                        .name("Too Many Bones")
                        .description("Affrontez des adversaires coriaces dans un jeu de combat coopératif riche en dés personnalisés et en progression de personnages.")
                        .price(new BigDecimal("89.90"))
                        .category("Coopératif")
                        .imageUrl("https://cf.geekdo-images.com/wKwRk0wYBcrtLAfgn4PCdg__itemrep/img/xKVF_SqBoULptBCjVdvHmpdsP0o=/fit-in/246x300/filters:strip_icc()/pic6624445.png")
                        .publisher("Chip Theory Games")
                        .minPlayers(1).maxPlayers(4).durationMinutes(120)
                        .stock(18)
                        .minAge(14)
                        .releaseDate(today.minusYears(9))
                        .tags(Set.of(tags.get("Coopératif"), tags.get("Dés"), tags.get("Combat")))
                        .build(),
                Game.builder()
                        .name("Mage Knight Board Game")
                        .description("Explorez, combattez et développez votre héros dans un jeu solo ou coopératif fantastique tres riche.")
                        .price(new BigDecimal("64.90"))
                        .category("Aventure")
                        .imageUrl("https://cf.geekdo-images.com/DUO2hz9AlLOH8p9ED-lCWg__itemrep/img/6OmGo3bidk3ma7U1v-oq_2pEJZI=/fit-in/246x300/filters:strip_icc()/pic1083380.jpg")
                        .publisher("WizKids")
                        .minPlayers(1).maxPlayers(4).durationMinutes(240)
                        .stock(19)
                        .minAge(14)
                        .releaseDate(today.minusYears(15))
                        .tags(Set.of(tags.get("Deck-building"), tags.get("Fantasy")))
                        .build(),
                Game.builder()
                        .name("Barrage")
                        .description("Contrôlez le marché de l'énergie hydroélectrique en construisant barrages et centrales dans un monde en pénurie d'eau.")
                        .price(new BigDecimal("64.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/jEPmWvvYpqkWrKOzqIHFsg__itemrep/img/-s65MFZDOx3Uf0Ec8Nol2nTBl5g=/fit-in/246x300/filters:strip_icc()/pic4336469.png")
                        .publisher("Cranio Creations")
                        .minPlayers(1).maxPlayers(4).durationMinutes(150)
                        .stock(20)
                        .minAge(14)
                        .releaseDate(today.minusYears(7))
                        .discountPercent(25)
                        .discountEndsAt(Instant.now().plus(7, ChronoUnit.DAYS))
                        .tags(Set.of(tags.get("Gestion de ressources")))
                        .build(),
                Game.builder()
                        .name("Hegemony: Lead Your Class to Victory")
                        .description("Incarnez une classe sociale (gouvernement, capital, ouvriers...) et négociez pour façonner la politique d'une nation.")
                        .price(new BigDecimal("59.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/DCLgJlrvB-EqL6A3WgQLMQ__itemrep/img/uQmSxTnX9ZoEGC5Mx6RECLSojQU=/fit-in/246x300/filters:strip_icc()/pic5715770.jpg")
                        .publisher("Hegemony Game")
                        .minPlayers(1).maxPlayers(4).durationMinutes(180)
                        .stock(21)
                        .minAge(14)
                        .releaseDate(today.minusYears(3))
                        .tags(Set.of(tags.get("Économie")))
                        .build(),
                Game.builder()
                        .name("Kanban EV")
                        .description("Gérez une chaîne de production automobile et optimisez chaque étape de fabrication d'une voiture électrique.")
                        .price(new BigDecimal("44.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/L2Wn-zUqkcHgqvwvY212Ig__itemrep/img/S_mg665DznHuiuvxvOIPk2mYwHM=/fit-in/246x300/filters:strip_icc()/pic4924232.jpg")
                        .publisher("PLAN B Games")
                        .minPlayers(1).maxPlayers(4).durationMinutes(100)
                        .stock(22)
                        .minAge(14)
                        .releaseDate(today.minusYears(6))
                        .tags(Set.of(tags.get("Gestion de ressources")))
                        .build(),
                Game.builder()
                        .name("Viticulture Essential Edition")
                        .description("Gérez un domaine viticole en Toscane, de la plantation des vignes à la vente du vin.")
                        .price(new BigDecimal("49.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/l_PRU2lVlX9seScRFcvFlA__itemrep/img/rfRBuKUlSgnnNpbRfy_osB9xrsM=/fit-in/246x300/filters:strip_icc()/pic6500949.jpg")
                        .publisher("Stonemaier Games")
                        .minPlayers(1).maxPlayers(6).durationMinutes(90)
                        .stock(23)
                        .minAge(13)
                        .releaseDate(today.minusYears(11))
                        .tags(Set.of(tags.get("Placement d'ouvriers")))
                        .build(),
                Game.builder()
                        .name("The Crew: Mission Deep Sea")
                        .description("Jeu de plis coopératif : communiquez sans parler pour remplir vos missions au fond de l'océan.")
                        .price(new BigDecimal("14.90"))
                        .category("Coopératif")
                        .imageUrl("https://cf.geekdo-images.com/VuBqZ1sMaDAVVHF_OEJP4g__itemrep/img/tgB3g7PECxG14yQ0FkMiMaXaOFE=/fit-in/246x300/filters:strip_icc()/pic5988903.jpg")
                        .publisher("Kosmos")
                        .minPlayers(2).maxPlayers(5).durationMinutes(20)
                        .stock(24)
                        .minAge(10)
                        .releaseDate(today.minusYears(5))
                        .tags(Set.of(tags.get("Coopératif"), tags.get("Cartes")))
                        .build(),
                Game.builder()
                        .name("Crokinole")
                        .description("Grand classique du jeu d'adresse : propulsez vos jetons pour atteindre le centre de la planche, tout en délogeant ceux de l'adversaire.")
                        .price(new BigDecimal("89.90"))
                        .category("Famille")
                        .imageUrl("https://cf.geekdo-images.com/DOwZ7_Q1w68iBhARcDAxig__itemrep/img/fP5bPqep8Rk1yaqL8FeJ7Ji2VrY=/fit-in/246x300/filters:strip_icc()/pic8549797.jpg")
                        .publisher("Neuf")
                        .minPlayers(2).maxPlayers(4).durationMinutes(30)
                        .stock(25)
                        .minAge(8)
                        .releaseDate(today.minusYears(150))
                        .tags(Set.of(tags.get("Abstrait")))
                        .build(),
                Game.builder()
                        .name("Everdell")
                        .description("Bâtissez une cite de petits animaux au fil des saisons, entre récolte de ressources et construction.")
                        .price(new BigDecimal("54.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/fjE7V5LNq31yVEW_yuqI-Q__itemrep/img/nyVhVuXdmw-1sigbocTKG81UInM=/fit-in/246x300/filters:strip_icc()/pic3918905.png")
                        .publisher("Starling Games")
                        .minPlayers(1).maxPlayers(4).durationMinutes(80)
                        .stock(26)
                        .minAge(13)
                        .releaseDate(today.minusYears(8))
                        .tags(Set.of(tags.get("Placement d'ouvriers")))
                        .build(),
                Game.builder()
                        .name("Heat: Pedal to the Metal")
                        .description("Course automobile à la gestion de main de cartes, entre surchauffe du moteur et dépassements risqués.")
                        .price(new BigDecimal("39.90"))
                        .category("Famille")
                        .imageUrl("https://cf.geekdo-images.com/-vOrd4bOspibyohYExLqWg__itemrep/img/mSj0nZUY3ofhIXFZJLGzF-6MQTg=/fit-in/246x300/filters:strip_icc()/pic6940449.png")
                        .publisher("Days of Wonder")
                        .minPlayers(1).maxPlayers(6).durationMinutes(75)
                        .stock(27)
                        .minAge(10)
                        .releaseDate(today.minusYears(4))
                        .tags(Set.of(tags.get("Cartes")))
                        .build(),
                Game.builder()
                        .name("Ticket to Ride Legacy: Legends of the West")
                        .description("Version legacy de Ticket to Ride : chaque partie modifie durablement le plateau et l'histoire de votre campagne.")
                        .price(new BigDecimal("44.90"))
                        .category("Famille")
                        .imageUrl("https://cf.geekdo-images.com/2H0pJddVJA3r6btqRNLG1g__itemrep/img/ikxhGFP6WVp1S6Q7zW7ccsiHCAY=/fit-in/246x300/filters:strip_icc()/pic7541330.png")
                        .publisher("Days of Wonder")
                        .minPlayers(2).maxPlayers(5).durationMinutes(60)
                        .stock(28)
                        .minAge(10)
                        .releaseDate(today.minusYears(3))
                        .tags(Set.of(tags.get("Campagne")))
                        .build(),
                Game.builder()
                        .name("Food Chain Magnate")
                        .description("Bâtissez un empire de restauration rapide et manipulez la chaîne de recrutement de vos employés.")
                        .price(new BigDecimal("64.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/Wtxml94LAXsIWQCxGPS63Q__itemrep/img/Bl9o9eur7lveoZUYwAl9LL9NSJo=/fit-in/246x300/filters:strip_icc()/pic2649434.png")
                        .publisher("Splotter Spellen")
                        .minPlayers(2).maxPlayers(5).durationMinutes(120)
                        .stock(29)
                        .minAge(14)
                        .releaseDate(today.minusYears(11))
                        .discountPercent(15)
                        .discountEndsAt(Instant.now().plus(14, ChronoUnit.DAYS))
                        .tags(Set.of(tags.get("Économie")))
                        .build(),
                Game.builder()
                        .name("Underwater Cities")
                        .description("Développez des cites sous-marines pour pallier la surpopulation terrestre, dans un jeu de gestion de ressources dense.")
                        .price(new BigDecimal("44.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/PwOwTVHovJAUQgghnGqCOg__itemrep/img/CHpbozXB266LtImU0nze5uXJ-HI=/fit-in/246x300/filters:strip_icc()/pic4837710.png")
                        .publisher("Delicious Games")
                        .minPlayers(1).maxPlayers(4).durationMinutes(100)
                        .stock(10)
                        .minAge(12)
                        .releaseDate(today.minusYears(8))
                        .tags(Set.of(tags.get("Gestion de ressources")))
                        .build(),
                Game.builder()
                        .name("Harmonies")
                        .description("Créez des paysages harmonieux en empilant des jetons colorés pour faire prospérer la faune.")
                        .price(new BigDecimal("34.90"))
                        .category("Famille")
                        .imageUrl("https://cf.geekdo-images.com/A_XP2_VN3ugyqPhezowB_w__itemrep/img/wGng6fVAYRI5NKBX6x-pksZKJGI=/fit-in/246x300/filters:strip_icc()/pic8026369.png")
                        .publisher("Libellud")
                        .minPlayers(1).maxPlayers(4).durationMinutes(50)
                        .stock(11)
                        .minAge(8)
                        .releaseDate(today.minusYears(2))
                        .tags(Set.of(tags.get("Abstrait")))
                        .build(),
                Game.builder()
                        .name("Pax Pamir: Second Edition")
                        .description("Manipulez alliances et trahisons entre empires rivaux pour le controle de l'Afghanistan au 19e siècle.")
                        .price(new BigDecimal("49.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/oSM_AuKYfGIwOtKbVEsoVg__itemrep/img/4yTV5vAsuDi8MZP6wWysZA8tmQg=/fit-in/246x300/filters:strip_icc()/pic4503733.png")
                        .publisher("Wehrlegig Games")
                        .minPlayers(1).maxPlayers(5).durationMinutes(180)
                        .stock(12)
                        .minAge(13)
                        .releaseDate(today.minusYears(7))
                        .build(),
                Game.builder()
                        .name("Cthulhu: Death May Die")
                        .description("Affrontez des horreurs cosmiques dans un jeu coopératif où la folie guette vos enquêteurs à chaque tour.")
                        .price(new BigDecimal("64.90"))
                        .category("Coopératif")
                        .imageUrl("https://cf.geekdo-images.com/SPpzri7fwLRgVWMKOocHxw__itemrep/img/kQzvJLDPXVGHwshKnyRo1x3Q9-s=/fit-in/246x300/filters:strip_icc()/pic9712872.png")
                        .publisher("CMON")
                        .minPlayers(1).maxPlayers(5).durationMinutes(90)
                        .stock(13)
                        .minAge(14)
                        .releaseDate(today.minusYears(7))
                        .tags(Set.of(tags.get("Coopératif"), tags.get("Combat")))
                        .build(),
                Game.builder()
                        .name("Age of Innovation")
                        .description("Suite spirituelle de Terra Mystica : développez votre civilisation sur un plateau modulaire.")
                        .price(new BigDecimal("64.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/D1vrcFEptCEoD8Z6s_iRfw__itemrep/img/hIfV87tcak-gBr2S2NGB-MAA230=/fit-in/246x300/filters:strip_icc()/pic7430993.jpg")
                        .publisher("Feuerland Spiele")
                        .minPlayers(1).maxPlayers(5).durationMinutes(150)
                        .stock(14)
                        .minAge(12)
                        .releaseDate(today.minusYears(3))
                        .tags(Set.of(tags.get("Civilisation")))
                        .build(),
                Game.builder()
                        .name("Puerto Rico")
                        .description("Grand classique de la gestion de ressources : développez plantations et batiments sur l'île de Puerto Rico.")
                        .price(new BigDecimal("39.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/QFiIRd2kimaMqTyWsX0aUg__itemrep/img/YDEozo5DfKYdDp8xi2mAfoV2qWk=/fit-in/246x300/filters:strip_icc()/pic158548.jpg")
                        .publisher("Ravensburger")
                        .minPlayers(2).maxPlayers(5).durationMinutes(150)
                        .stock(15)
                        .minAge(12)
                        .releaseDate(today.minusYears(24))
                        .tags(Set.of(tags.get("Gestion de ressources")))
                        .build(),
                Game.builder()
                        .name("On Mars")
                        .description("Dirigez la première colonie humaine sur Mars, entre survie, extraction de ressources et exploration.")
                        .price(new BigDecimal("64.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/Nm0Iw8NoiM9V8IsifimGBw__itemrep/img/xTjuZwi_7iS6FpZIISWTk7SAZ5o=/fit-in/246x300/filters:strip_icc()/pic4357658.jpg")
                        .publisher("Eagle-Gryphon Games")
                        .minPlayers(1).maxPlayers(4).durationMinutes(240)
                        .stock(16)
                        .minAge(14)
                        .releaseDate(today.minusYears(6))
                        .tags(Set.of(tags.get("Science-fiction"), tags.get("Gestion de ressources")))
                        .build(),
                Game.builder()
                        .name("Anachrony")
                        .description("Après un cataclysme, voyagez dans le temps pour reconstruire la civilisation avant qu'il ne soit trop tard.")
                        .price(new BigDecimal("69.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/31quLNzteInnevVRAABoow__itemrep/img/arsLLQqoHPgt3yXqvc-AydPFHVw=/fit-in/246x300/filters:strip_icc()/pic3499707.jpg")
                        .publisher("Mindclash Games")
                        .minPlayers(1).maxPlayers(4).durationMinutes(150)
                        .stock(17)
                        .minAge(14)
                        .releaseDate(today.minusYears(9))
                        .tags(Set.of(tags.get("Science-fiction")))
                        .build(),
                Game.builder()
                        .name("Caverna: The Cave Farmers")
                        .description("Développez une famille de nains, entre agriculture, élevage et exploration de cavernes.")
                        .price(new BigDecimal("54.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/EAqbd46lFxo-7GumlO8U4w__itemrep/img/hK1HuYlFD4sSigzPa2RsHRNF0qk=/fit-in/246x300/filters:strip_icc()/pic5598833.jpg")
                        .publisher("Lookout Games")
                        .minPlayers(1).maxPlayers(7).durationMinutes(150)
                        .stock(18)
                        .minAge(12)
                        .releaseDate(today.minusYears(13))
                        .discountPercent(20)
                        .discountEndsAt(Instant.now().plus(10, ChronoUnit.DAYS))
                        .tags(Set.of(tags.get("Placement d'ouvriers")))
                        .build(),
                Game.builder()
                        .name("Oathsworn: Into the Deepwood")
                        .description("Aventure narrative coopérative dans une forêt hantee, riche en combats tactiques et en choix scénarisés.")
                        .price(new BigDecimal("119.90"))
                        .category("Aventure")
                        .imageUrl("https://cf.geekdo-images.com/dezQ4YjF03lZVxTdI-UJYw__itemrep/img/EvlCkFc6GoEoWdCwDageBn59kx4=/fit-in/246x300/filters:strip_icc()/pic6863204.jpg")
                        .publisher("Shattered Void Games")
                        .minPlayers(1).maxPlayers(4).durationMinutes(150)
                        .stock(19)
                        .minAge(14)
                        .releaseDate(today.minusYears(4))
                        .tags(Set.of(tags.get("Coopératif"), tags.get("Combat")))
                        .build(),
                Game.builder()
                        .name("The Lord of the Rings: Fate of the Fellowship")
                        .description("Guidez la Communauté à travers la Terre du Milieu dans un jeu narratif coopératif à choix multiples.")
                        .price(new BigDecimal("49.90"))
                        .category("Coopératif")
                        .imageUrl("https://cf.geekdo-images.com/scw36iBIad7l-rGzxPGcGg__itemrep/img/UkJy_2ut0G5krsR6wZv_r1Plmto=/fit-in/246x300/filters:strip_icc()/pic8662670.png")
                        .publisher("Fantasy Flight Games")
                        .minPlayers(1).maxPlayers(5).durationMinutes(90)
                        .stock(20)
                        .minAge(12)
                        .releaseDate(today.plusMonths(3))
                        .tags(Set.of(tags.get("Coopératif"), tags.get("Fantasy")))
                        .build(),
                Game.builder()
                        .name("Agricola")
                        .description("Développez votre ferme, nourrissez votre famille et exploitez au mieux vos champs et votre bétail.")
                        .price(new BigDecimal("49.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/3L6ZtOll9W5O6-3-EwSMyw__itemrep/img/8VVXhLllK6HGLr406rykMMFimUQ=/fit-in/246x300/filters:strip_icc()/pic1899157.jpg")
                        .publisher("Lookout Games")
                        .minPlayers(1).maxPlayers(5).durationMinutes(150)
                        .stock(21)
                        .minAge(12)
                        .releaseDate(today.minusYears(19))
                        .tags(Set.of(tags.get("Placement d'ouvriers")))
                        .build(),
                Game.builder()
                        .name("Blood on the Clocktower")
                        .description("Jeu social de déduction pour grand groupe : démasquez les démons cachés parmi les villageois avant l'aube.")
                        .price(new BigDecimal("89.90"))
                        .category("Ambiance")
                        .imageUrl("https://cf.geekdo-images.com/HINb2nkFn5IiZxAlzQIs4g__itemrep/img/ji9nruIqJkNi8omWgNRZKmrZjwA=/fit-in/246x300/filters:strip_icc()/pic7009391.jpg")
                        .publisher("The Pandemonium Institute")
                        .minPlayers(5).maxPlayers(20).durationMinutes(90)
                        .stock(22)
                        .minAge(15)
                        .releaseDate(today.minusYears(4))
                        .tags(Set.of(tags.get("Bluff")))
                        .build(),
                Game.builder()
                        .name("Blood Rage")
                        .description("Menez votre clan viking vers un Ragnarök glorieux, entre combats, quêtes et pillage.")
                        .price(new BigDecimal("64.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/HkZSJfQnZ3EpS214xtuplg__itemrep/img/ZSJhCapvtPoiIQZ1XdfO-qgUuFY=/fit-in/246x300/filters:strip_icc()/pic2439223.jpg")
                        .publisher("CMON")
                        .minPlayers(2).maxPlayers(4).durationMinutes(90)
                        .stock(23)
                        .minAge(14)
                        .releaseDate(today.minusYears(11))
                        .tags(Set.of(tags.get("Combat"), tags.get("Draft")))
                        .build(),
                Game.builder()
                        .name("Obsession")
                        .description("Gérez un domaine dans l'Angleterre victorienne et grimpez les échelons de la haute société.")
                        .price(new BigDecimal("54.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/sy89BiuZXfbSnG7Cag9tBQ__itemrep/img/_1IdpMxkMKCR0bx-7E8mbh3nqzM=/fit-in/246x300/filters:strip_icc()/pic5902073.png")
                        .publisher("Kayenta Games")
                        .minPlayers(2).maxPlayers(4).durationMinutes(150)
                        .stock(24)
                        .minAge(14)
                        .releaseDate(today.minusYears(8))
                        .tags(Set.of(tags.get("Gestion de ressources")))
                        .build(),
                Game.builder()
                        .name("Grand Austria Hôtel")
                        .description("Gérez un hôtel viennois prestigieux en accueillant les bons clients au bon moment.")
                        .price(new BigDecimal("39.90"))
                        .category("Stratégie")
                        .imageUrl("undefined")
                        .publisher("eggertspiele")
                        .minPlayers(2).maxPlayers(4).durationMinutes(90)
                        .stock(25)
                        .minAge(12)
                        .releaseDate(today.minusYears(11))
                        .tags(Set.of(tags.get("Dés")))
                        .build(),
                Game.builder()
                        .name("Lisboa")
                        .description("Reconstruisez Lisbonne après le séisme de 1755 en gérant commerce, industrie et influence politique.")
                        .price(new BigDecimal("69.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/OrHS8_a1CqSGiXeTfCk0Wg__itemrep/img/3OmJPCYr0wEQQD5dIgW9YxY5hxQ=/fit-in/246x300/filters:strip_icc()/pic3209553.jpg")
                        .publisher("Eagle-Gryphon Games")
                        .minPlayers(1).maxPlayers(4).durationMinutes(240)
                        .stock(26)
                        .minAge(14)
                        .releaseDate(today.minusYears(9))
                        .tags(Set.of(tags.get("Économie")))
                        .build(),
                Game.builder()
                        .name("Endeavor: Deep Sea")
                        .description("Explorez les profondeurs océaniques et développez votre influence sous-marine dans cette suite d'Endeavor.")
                        .price(new BigDecimal("44.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/wIbevITv9W79ELP8rEZoKA__itemrep/img/iSGn7egis5jFfnLDTjmpkR6CT_g=/fit-in/246x300/filters:strip_icc()/pic6996584.jpg")
                        .publisher("Off the Page Games")
                        .minPlayers(1).maxPlayers(5).durationMinutes(90)
                        .stock(27)
                        .minAge(12)
                        .releaseDate(today.minusYears(2))
                        .discountPercent(10)
                        .discountEndsAt(Instant.now().plus(21, ChronoUnit.DAYS))
                        .tags(Set.of(tags.get("Exploration")))
                        .build(),
                Game.builder()
                        .name("The White Castle")
                        .description("Servez l'empereur dans le Japon féodal en placant vos ouvriers autour du château blanc d'Edo.")
                        .price(new BigDecimal("34.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/qXT1U-nFh9PE8ujfdmI7dA__itemrep/img/4VpX36FMypCo-iRbA_dkP9lhi-8=/fit-in/246x300/filters:strip_icc()/pic7754663.jpg")
                        .publisher("Devir")
                        .minPlayers(1).maxPlayers(4).durationMinutes(60)
                        .stock(28)
                        .minAge(12)
                        .releaseDate(today.minusYears(3))
                        .tags(Set.of(tags.get("Placement d'ouvriers")))
                        .build(),
                Game.builder()
                        .name("Sleeping Gods")
                        .description("Explorez un monde mystérieux à bord de votre navire échoué, dans une aventure narrative à choix multiples.")
                        .price(new BigDecimal("84.90"))
                        .category("Aventure")
                        .imageUrl("https://cf.geekdo-images.com/Zdt8l4oTBpFICsMyNof7Jg__itemrep/img/gGT6XPcKdYS-3EIOKd-WT5zu2qY=/fit-in/246x300/filters:strip_icc()/pic5975244.png")
                        .publisher("Red Raven Games")
                        .minPlayers(1).maxPlayers(4).durationMinutes(90)
                        .stock(29)
                        .minAge(13)
                        .releaseDate(today.minusYears(5))
                        .tags(Set.of(tags.get("Exploration")))
                        .build(),
                Game.builder()
                        .name("Power Grid")
                        .description("Développez un réseau électrique en achetant centrales et ressources pour alimenter le plus de villes possible.")
                        .price(new BigDecimal("44.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/yd6LuatytHRhcFCxCf-EEg__itemrep/img/LsqKzcnoaVUlSUmLxFE8dwxFndk=/fit-in/246x300/filters:strip_icc()/pic4459753.jpg")
                        .publisher("Rio Grande Games")
                        .minPlayers(2).maxPlayers(6).durationMinutes(120)
                        .stock(10)
                        .minAge(12)
                        .releaseDate(today.minusYears(22))
                        .tags(Set.of(tags.get("Économie"), tags.get("Enchères")))
                        .build(),
                Game.builder()
                        .name("Tzolk'in: The Mayan Calendar")
                        .description("Placez vos ouvriers sur des engrenages mayas en mouvement pour récolter ressources et technologies.")
                        .price(new BigDecimal("54.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/kXf7mDyDYuHg6oe8yTUIEA__itemrep/img/8M-vck69HAdoJdStBZ8q91-7hRs=/fit-in/246x300/filters:strip_icc()/pic4604439.jpg")
                        .publisher("Czech Games Edition")
                        .minPlayers(2).maxPlayers(4).durationMinutes(120)
                        .stock(11)
                        .minAge(13)
                        .releaseDate(today.minusYears(14))
                        .tags(Set.of(tags.get("Placement d'ouvriers")))
                        .build(),
                Game.builder()
                        .name("Clans of Caledonia")
                        .description("Développez votre clan écossais entre élevage, production et commerce international.")
                        .price(new BigDecimal("44.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/SPuwc6RJ6y4PnTH36Pegsg__itemrep/img/xxhvhwGExrMMiLD9lcsUvQoKxU8=/fit-in/246x300/filters:strip_icc()/pic3511783.png")
                        .publisher("Karma Games")
                        .minPlayers(1).maxPlayers(4).durationMinutes(100)
                        .stock(12)
                        .minAge(12)
                        .releaseDate(today.minusYears(9))
                        .tags(Set.of(tags.get("Gestion de ressources")))
                        .build(),
                Game.builder()
                        .name("Mansions of Madness: Second Edition")
                        .description("Enquête horrifique coopérative pilotée par une application, dans l'univers du mythe de Cthulhu.")
                        .price(new BigDecimal("79.90"))
                        .category("Coopératif")
                        .imageUrl("https://cf.geekdo-images.com/LIooA9bTdjnE9qmhjL-UFw__itemrep/img/G_-z236LOfeZMfomDg5oPNJvyrg=/fit-in/246x300/filters:strip_icc()/pic3118622.jpg")
                        .publisher("Fantasy Flight Games")
                        .minPlayers(1).maxPlayers(5).durationMinutes(180)
                        .stock(13)
                        .minAge(14)
                        .releaseDate(today.minusYears(10))
                        .tags(Set.of(tags.get("Coopératif")))
                        .build(),
                Game.builder()
                        .name("The Quacks of Quedlinburg")
                        .description("Composez des potions explosives en piochant des ingrédients dans votre sac, sans dépasser la limite de danger.")
                        .price(new BigDecimal("29.90"))
                        .category("Famille")
                        .imageUrl("https://cf.geekdo-images.com/B1bLRWzTASZ-xx9NoAE79A__itemrep/img/gBYgKZ_1JWxGnvnxw8570K65kXQ=/fit-in/246x300/filters:strip_icc()/pic8780293.png")
                        .publisher("Czech Games Edition")
                        .minPlayers(2).maxPlayers(4).durationMinutes(45)
                        .stock(14)
                        .minAge(10)
                        .releaseDate(today.minusYears(8))
                        .tags(Set.of(tags.get("Dés")))
                        .build(),
                Game.builder()
                        .name("Voidfall")
                        .description("Guerre spatiale asymétrique en 4X, entre technologie, diplomatie et expansion territoriale.")
                        .price(new BigDecimal("99.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/hItZjdDTNuaCZ7fEztwcUQ__itemrep/img/Uzot_otbvYXpwkTpnc1uwiXUWqs=/fit-in/246x300/filters:strip_icc()/pic6153324.jpg")
                        .publisher("Kraken Miniatures")
                        .minPlayers(1).maxPlayers(6).durationMinutes(240)
                        .stock(15)
                        .minAge(14)
                        .releaseDate(today.minusYears(3))
                        .tags(Set.of(tags.get("Science-fiction")))
                        .build(),
                Game.builder()
                        .name("Paladins of the West Kingdom")
                        .description("Défendez les frontières du royaume en recrutant des habitants, entre vertu et corruption.")
                        .price(new BigDecimal("49.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/4nhokcLdYoo6ulbZ1rmGgA__itemrep/img/2YT-EqfAb6vwxDSrFQMSm-luQAs=/fit-in/246x300/filters:strip_icc()/pic4462987.png")
                        .publisher("Renegade Game Studios")
                        .minPlayers(1).maxPlayers(4).durationMinutes(120)
                        .stock(16)
                        .minAge(12)
                        .releaseDate(today.minusYears(7))
                        .discountPercent(25)
                        .discountEndsAt(Instant.now().plus(7, ChronoUnit.DAYS))
                        .tags(Set.of(tags.get("Placement d'ouvriers")))
                        .build(),
                Game.builder()
                        .name("Le Havre")
                        .description("Gérez le port du Havre, entre extraction de ressources, industrie et commerce maritime.")
                        .price(new BigDecimal("44.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/y7Rqd3S6J7vyVhicR1bqTQ__itemrep/img/4Ks1jgI4QIqGjDjsOPIk9fJuLIE=/fit-in/246x300/filters:strip_icc()/pic6091101.jpg")
                        .publisher("Lookout Games")
                        .minPlayers(1).maxPlayers(5).durationMinutes(220)
                        .stock(17)
                        .minAge(12)
                        .releaseDate(today.minusYears(18))
                        .tags(Set.of(tags.get("Gestion de ressources")))
                        .build(),
                Game.builder()
                        .name("Android: Netrunner")
                        .description("Duel asymétrique cyberpunk entre une mégacorporation et un hacker infiltré dans ses réseaux.")
                        .price(new BigDecimal("34.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/2ewHIIG_TRq8bYlqk0jIMw__itemrep/img/Nz7z5Qk3fZ3R6IM14pDRg1D8XKE=/fit-in/246x300/filters:strip_icc()/pic3738560.jpg")
                        .publisher("Fantasy Flight Games")
                        .minPlayers(2).maxPlayers(2).durationMinutes(45)
                        .stock(18)
                        .minAge(14)
                        .releaseDate(today.minusYears(14))
                        .tags(Set.of(tags.get("Cartes")))
                        .build(),
                Game.builder()
                        .name("The Gallerist")
                        .description("Gérez une galerie d'art, de l'acquisition d'œuvres à l'organisation de ventes aux enchères prestigieuses.")
                        .price(new BigDecimal("64.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/ie1GSt1XV04sXQXt-3O1UQ__itemrep/img/HBQJFsyK0mDMgd_DKxD4Xmhi4UA=/fit-in/246x300/filters:strip_icc()/pic2503200.png")
                        .publisher("Czech Games Edition")
                        .minPlayers(1).maxPlayers(4).durationMinutes(150)
                        .stock(19)
                        .minAge(13)
                        .releaseDate(today.minusYears(11))
                        .tags(Set.of(tags.get("Placement d'ouvriers"), tags.get("Enchères")))
                        .build(),
                Game.builder()
                        .name("Dominion")
                        .description("Le jeu fondateur du deck-building : bâtissez le deck le plus efficace pour développer votre royaume.")
                        .price(new BigDecimal("34.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/j6iQpZ4XkemZP07HNCODBA__itemrep/img/_QiaiFj-LGZoqdatE-wVqNaYWx8=/fit-in/246x300/filters:strip_icc()/pic394356.jpg")
                        .publisher("Rio Grande Games")
                        .minPlayers(2).maxPlayers(4).durationMinutes(30)
                        .stock(20)
                        .minAge(13)
                        .releaseDate(today.minusYears(18))
                        .tags(Set.of(tags.get("Deck-building")))
                        .build(),
                Game.builder()
                        .name("Aeon's End")
                        .description("Défendez Gravehold contre des créatures abyssales dans un deck-building coopératif à l'ordre de pioche inversé.")
                        .price(new BigDecimal("44.90"))
                        .category("Coopératif")
                        .imageUrl("https://cf.geekdo-images.com/d50LceHj6LIafa4S_qIsCg__itemrep/img/Uswnuak6armCO4JWTi5_03kl0eo=/fit-in/246x300/filters:strip_icc()/pic3189350.jpg")
                        .publisher("Indie Boards & Cards")
                        .minPlayers(1).maxPlayers(4).durationMinutes(90)
                        .stock(21)
                        .minAge(14)
                        .releaseDate(today.minusYears(10))
                        .tags(Set.of(tags.get("Coopératif"), tags.get("Deck-building")))
                        .build(),
                Game.builder()
                        .name("Catan: Seafarers")
                        .description("Prenez la mer pour explorer et coloniser de nouvelles îles au-delà de Catane. Extension pour Catane.")
                        .price(new BigDecimal("29.90"))
                        .category("Extension")
                        .imageUrl("https://cf.geekdo-images.com/v8ll_1CxVGP-KN-NqkoQsg__itemrep/img/_Afku52eDoM-dvLisuOBVG5c9VQ=/fit-in/246x300/filters:strip_icc()/pic8828019.jpg")
                        .publisher("Kosmos")
                        .minPlayers(2).maxPlayers(4).durationMinutes(60)
                        .stock(8)
                        .minAge(12)
                        .releaseDate(today.minusYears(29))
                        .build(),
                Game.builder()
                        .name("Catan: Cities & Knights")
                        .description("Défendez Catane contre les barbares et développez vos villes en cites fortifiées. Extension pour Catane.")
                        .price(new BigDecimal("34.90"))
                        .category("Extension")
                        .imageUrl("https://cf.geekdo-images.com/CQHOCJI6EFUUsQiGXS9oHg__itemrep/img/cp_pm-1W59H9qbbAwhEg8Ycy1y4=/fit-in/246x300/filters:strip_icc()/pic8828016.jpg")
                        .publisher("Kosmos")
                        .minPlayers(2).maxPlayers(4).durationMinutes(60)
                        .stock(9)
                        .minAge(12)
                        .releaseDate(today.minusYears(28))
                        .build(),
                Game.builder()
                        .name("Catan: 5-6 Player Expansion")
                        .description("Accueillez jusqu'à six joueurs autour de l'île de Catane. Extension pour Catane.")
                        .price(new BigDecimal("24.90"))
                        .category("Extension")
                        .imageUrl("https://cf.geekdo-images.com/tsDqjx3IqOl4r613Qh6-zQ__itemrep/img/mYxE-HHdsUsoZdXpilRQJJd1ZOI=/fit-in/246x300/filters:strip_icc()/pic8828033.jpg")
                        .publisher("Kosmos")
                        .minPlayers(2).maxPlayers(4).durationMinutes(60)
                        .stock(10)
                        .minAge(12)
                        .releaseDate(today.minusYears(30))
                        .build(),
                Game.builder()
                        .name("Carcassonne: The River")
                        .description("Ajoutez une rivière sinueuse pour varier le tracé des paysages de Carcassonne. Extension pour Carcassonne.")
                        .price(new BigDecimal("12.90"))
                        .category("Extension")
                        .imageUrl("https://cf.geekdo-images.com/qCiVmugRuY47bf9YFXlQ8A__itemrep/img/E1VpQHh8qsJlzQnnbmsentR85YA=/fit-in/246x300/filters:strip_icc()/pic193765.jpg")
                        .publisher("Hans im Gluck")
                        .minPlayers(2).maxPlayers(4).durationMinutes(60)
                        .stock(11)
                        .minAge(12)
                        .releaseDate(today.minusYears(25))
                        .build(),
                Game.builder()
                        .name("Carcassonne: Inns & Cathedrals")
                        .description("Ajoutez auberges et cathédrales pour de nouvelles stratégies de score à Carcassonne. Extension pour Carcassonne.")
                        .price(new BigDecimal("24.90"))
                        .category("Extension")
                        .imageUrl("https://cf.geekdo-images.com/9W3DkpIZwD-CrQrzfewG1Q__itemrep/img/EIILrKhHv2DjTJ_Lw4Qx9oGSJ8w=/fit-in/246x300/filters:strip_icc()/pic9210962.jpg")
                        .publisher("Hans im Gluck")
                        .minPlayers(2).maxPlayers(4).durationMinutes(60)
                        .stock(12)
                        .minAge(12)
                        .releaseDate(today.minusYears(24))
                        .build(),
                Game.builder()
                        .name("7 Wonders: Leaders")
                        .description("Recrutez des personnages historiques célèbres pour renforcer votre civilisation dans 7 Wonders. Extension pour 7 Wonders.")
                        .price(new BigDecimal("24.90"))
                        .category("Extension")
                        .imageUrl("https://cf.geekdo-images.com/S8YmOOnFFI58OZ3bBM2A7w__itemrep/img/HLSgN1JPcTpBO3yvbLzJqzc8m5g=/fit-in/246x300/filters:strip_icc()/pic1046319.jpg")
                        .publisher("Repos Production")
                        .minPlayers(2).maxPlayers(4).durationMinutes(60)
                        .stock(13)
                        .minAge(12)
                        .releaseDate(today.minusYears(15))
                        .build(),
                Game.builder()
                        .name("Terraforming Mars: Prelude")
                        .description("Accélérez le debut de partie de Terraforming Mars avec de nouvelles cartes projet. Extension pour Terraforming Mars.")
                        .price(new BigDecimal("19.90"))
                        .category("Extension")
                        .imageUrl("https://cf.geekdo-images.com/2qrpbgsKEcvu5RLXpb6fgw__itemrep/img/R-Gq_KB53LC-GbGXsIrV_ljhkqs=/fit-in/246x300/filters:strip_icc()/pic4137234.jpg")
                        .publisher("FryxGames")
                        .minPlayers(2).maxPlayers(4).durationMinutes(60)
                        .stock(14)
                        .minAge(12)
                        .releaseDate(today.minusYears(8))
                        .build(),
                Game.builder()
                        .name("Wingspan: European Expansion")
                        .description("Accueillez de nouvelles espèces d'oiseaux européens dans vos réserves Wingspan. Extension pour Wingspan.")
                        .price(new BigDecimal("24.90"))
                        .category("Extension")
                        .imageUrl("https://cf.geekdo-images.com/7izK8WM_bgtvBzxQvLGz-A__itemrep/img/3T9Ul4e8mMOGpzr7LOIMvUmhM4s=/fit-in/246x300/filters:strip_icc()/pic4982682.jpg")
                        .publisher("Stonemaier Games")
                        .minPlayers(2).maxPlayers(4).durationMinutes(60)
                        .stock(15)
                        .minAge(12)
                        .releaseDate(today.minusYears(7))
                        .build(),
                Game.builder()
                        .name("Splendor: Cities of Splendor")
                        .description("Trois nouveaux modules pour varier vos parties de Splendor : cités, orients et commerce. Extension pour Splendor.")
                        .price(new BigDecimal("19.90"))
                        .category("Extension")
                        .imageUrl("https://cf.geekdo-images.com/H7YUcZPxhbq2fPuzuxODlg__itemrep/img/4FtjYL7XzUeVuSX8eXZP2Sbb5P4=/fit-in/246x300/filters:strip_icc()/pic3711701.jpg")
                        .publisher("Space Cowboys")
                        .minPlayers(2).maxPlayers(4).durationMinutes(60)
                        .stock(16)
                        .minAge(12)
                        .releaseDate(today.minusYears(8))
                        .build(),
                Game.builder()
                        .name("Pandemic: On the Brink")
                        .description("De nouveaux roles, un mode compétitif et la mutation bioterroriste pour corser Pandemic. Extension pour Pandemic.")
                        .price(new BigDecimal("29.90"))
                        .category("Extension")
                        .imageUrl("https://cf.geekdo-images.com/MOsfIJrEqkGMUlo09TL3rw__itemrep/img/ZtVyDma9hoE7_x_jDU39oo5lQ6Q=/fit-in/246x300/filters:strip_icc()/pic7014070.jpg")
                        .publisher("Z-Man Games")
                        .minPlayers(2).maxPlayers(4).durationMinutes(60)
                        .stock(17)
                        .minAge(12)
                        .releaseDate(today.minusYears(17))
                        .build(),
                Game.builder()
                        .name("Nemesis: Lockdown")
                        .description("Une nouvelle campagne sur une base lunaire assiégée, jouable seule ou liée à Nemesis. Extension pour Nemesis.")
                        .price(new BigDecimal("69.90"))
                        .category("Extension")
                        .imageUrl("https://cf.geekdo-images.com/NEbmFFGhKwegIryUArgw6w__itemrep/img/G7o8HqRjdYYNL2Hj9iOTnsGanAQ=/fit-in/246x300/filters:strip_icc()/pic7110034.jpg")
                        .publisher("Awaken Realms")
                        .minPlayers(2).maxPlayers(4).durationMinutes(60)
                        .stock(18)
                        .minAge(12)
                        .releaseDate(today.minusYears(4))
                        .build(),
                Game.builder()
                        .name("Dune: Imperium – Uprising")
                        .description("Grande extension autonome de Dune: Imperium avec de nouvelles factions et un plateau modulaire. Extension pour Dune: Imperium.")
                        .price(new BigDecimal("49.90"))
                        .category("Extension")
                        .imageUrl("https://cf.geekdo-images.com/UVUkjMV_Q2paVUIUP30Vvw__itemrep/img/ZQPDp9gumb19lmgdAvNMf5XN_c0=/fit-in/246x300/filters:strip_icc()/pic7664424.jpg")
                        .publisher("Dire Wolf")
                        .minPlayers(2).maxPlayers(4).durationMinutes(60)
                        .stock(19)
                        .minAge(12)
                        .releaseDate(today.minusYears(3))
                        .build(),
                Game.builder()
                        .name("Dominion: Intrigue")
                        .description("De nouvelles cartes royaume centrées sur l'interaction directe entre joueurs, pour Dominion. Extension pour Dominion.")
                        .price(new BigDecimal("29.90"))
                        .category("Extension")
                        .imageUrl("https://cf.geekdo-images.com/OGOmpi0GgwOwH2y28QgkuA__itemrep/img/BUiLGjf1tVpnUsg9WEyRq1HXAL4=/fit-in/246x300/filters:strip_icc()/pic460011.jpg")
                        .publisher("Rio Grande Games")
                        .minPlayers(2).maxPlayers(4).durationMinutes(60)
                        .stock(20)
                        .minAge(12)
                        .releaseDate(today.minusYears(17))
                        .build(),
                Game.builder()
                        .name("Concordia Venus")
                        .description("Ajoutez la déesse Venus et de nouvelles cartes personnage à vos parties de Concordia. Extension pour Concordia.")
                        .price(new BigDecimal("19.90"))
                        .category("Extension")
                        .imageUrl("https://cf.geekdo-images.com/36WIe0ZHkp5OvHOlB-8vog__itemrep/img/_lJIROiyeLhIZi7z9XO3Wt9w7wA=/fit-in/246x300/filters:strip_icc()/pic4356580.jpg")
                        .publisher("PD-Verlag")
                        .minPlayers(2).maxPlayers(4).durationMinutes(60)
                        .stock(21)
                        .minAge(12)
                        .releaseDate(today.minusYears(8))
                        .build(),
                Game.builder()
                        .name("Too Many Bones: Undertow")
                        .description("De nouveaux Gearlocs et adversaires aquatiques pour prolonger l'aventure de Too Many Bones. Extension pour Too Many Bones.")
                        .price(new BigDecimal("79.90"))
                        .category("Extension")
                        .imageUrl("https://cf.geekdo-images.com/AGN1PRSFmhdUyoTjd-qw8A__itemrep/img/fHRjGQjkkA5aZuX9iqx5Bx85Qmg=/fit-in/246x300/filters:strip_icc()/pic3752850.jpg")
                        .publisher("Chip Theory Games")
                        .minPlayers(2).maxPlayers(4).durationMinutes(60)
                        .stock(22)
                        .minAge(12)
                        .releaseDate(today.minusYears(8))
                        .build(),
                Game.builder()
                        .name("Aeon's End: War Eternal")
                        .description("De nouveaux mages et Nemesis pour prolonger la défense coopérative d'Aeon's End. Extension pour Aeon's End.")
                        .price(new BigDecimal("34.90"))
                        .category("Extension")
                        .imageUrl("https://cf.geekdo-images.com/H2st1bZH4O0FM46NhKMqyQ__itemrep/img/NmbNKxUlppKYYJFNxqn7GEDnwPg=/fit-in/246x300/filters:strip_icc()/pic3430893.jpg")
                        .publisher("Indie Boards & Cards")
                        .minPlayers(2).maxPlayers(4).durationMinutes(60)
                        .stock(8)
                        .minAge(12)
                        .releaseDate(today.minusYears(9))
                        .build(),
                Game.builder()
                        .name("Kingdomino")
                        .description("Assemblez vos dominos royaume après royaume pour bâtir le plus prospère des territoires.")
                        .price(new BigDecimal("24.90"))
                        .category("Famille")
                        .imageUrl("https://cf.geekdo-images.com/c0m3gwZTcfKoLI63ASio8g__itemrep/img/HBQW09mf1nlYLGF4jmB9jfm4_EI=/fit-in/246x300/filters:strip_icc()/pic8443569.png")
                        .publisher("Blue Orange")
                        .minPlayers(2).maxPlayers(4).durationMinutes(20)
                        .stock(28)
                        .minAge(8)
                        .releaseDate(today.minusYears(10))
                        .tags(Set.of(tags.get("Pose de tuiles")))
                        .build(),
                Game.builder()
                        .name("Sagrada")
                        .description("Composez un vitrail à partir de dés colorés, en respectant des contraintes de couleur et de valeur.")
                        .price(new BigDecimal("34.90"))
                        .category("Stratégie")
                        .imageUrl("https://cf.geekdo-images.com/77OxPP4ckbOgK9sPg-6KDw__itemrep/img/83w34rcD6VctDmBqAj6VmcTs6eg=/fit-in/246x300/filters:strip_icc()/pic9374520.png")
                        .publisher("Floodgate Games")
                        .minPlayers(1).maxPlayers(4).durationMinutes(45)
                        .stock(20)
                        .minAge(14)
                        .releaseDate(today.minusYears(9))
                        .tags(Set.of(tags.get("Abstrait"), tags.get("Dés")))
                        .build(),
                Game.builder()
                        .name("Wavelength")
                        .description("Devinez où se situe le curseur sur une échelle, en interprétant l'indice donné par votre coéquipier.")
                        .price(new BigDecimal("29.90"))
                        .category("Party Game")
                        .imageUrl("https://cf.geekdo-images.com/z4fbPdmJg_5yphJEvql4ZA__itemrep/img/Dnjsh4DWMkiZBsPszNWs8bqtvGY=/fit-in/246x300/filters:strip_icc()/pic4552862.png")
                        .publisher("Palm Court")
                        .minPlayers(2).maxPlayers(12).durationMinutes(45)
                        .stock(24)
                        .minAge(14)
                        .releaseDate(today.minusYears(7))
                        .build()
        ));
    }

    /**
     * Relie chaque extension a son jeu de base (voir GameService#getRelatedGames),
     * par nom plutot que par reference directe pour ne pas restructurer seedGames().
     */
    private void linkExpansions() {
        List<Game> games = gameRepository.findAll();
        if (games.stream().anyMatch(g -> g.getBaseGame() != null)) {
            return;
        }

        Map<String, Game> byName = games.stream().collect(Collectors.toMap(Game::getName, g -> g));
        Map<String, String> expansionToBase = Map.ofEntries(
                Map.entry("Catan: Seafarers", "Catane"),
                Map.entry("Catan: Cities & Knights", "Catane"),
                Map.entry("Catan: 5-6 Player Expansion", "Catane"),
                Map.entry("Carcassonne: The River", "Carcassonne"),
                Map.entry("Carcassonne: Inns & Cathedrals", "Carcassonne"),
                Map.entry("7 Wonders: Leaders", "7 Wonders"),
                Map.entry("Terraforming Mars: Prelude", "Terraforming Mars"),
                Map.entry("Wingspan: European Expansion", "Wingspan"),
                Map.entry("Splendor: Cities of Splendor", "Splendor"),
                Map.entry("Pandemic: On the Brink", "Pandemic"),
                Map.entry("Nemesis: Lockdown", "Nemesis"),
                Map.entry("Dune: Imperium – Uprising", "Dune: Imperium"),
                Map.entry("Dominion: Intrigue", "Dominion"),
                Map.entry("Concordia Venus", "Concordia"),
                Map.entry("Too Many Bones: Undertow", "Too Many Bones"),
                Map.entry("Aeon's End: War Eternal", "Aeon's End")
        );

        expansionToBase.forEach((expansionName, baseName) -> {
            Game expansion = byName.get(expansionName);
            Game base = byName.get(baseName);
            if (expansion != null && base != null) {
                expansion.setBaseGame(base);
                gameRepository.save(expansion);
            }
        });
    }

    /**
     * Une commande livrée + quelques avis, pour que la page d'accueil (avis
     * récents, top ventes) ne soit pas vide au premier démarrage.
     */
    private void seedOrderAndReviews() {
        if (orderRepository.count() > 0) {
            return;
        }

        User buyer = userRepository.findByEmail("user@bgs.fr")
                .orElseThrow(() -> new IllegalStateException("Utilisateur de démo introuvable"));
        List<Game> games = gameRepository.findAll();
        Game catane = findByName(games, "Catane");
        Game pandemic = findByName(games, "Pandemic");
        Game azul = findByName(games, "Azul");

        Order order = Order.builder()
                .user(buyer)
                .createdAt(Instant.now().minus(5, ChronoUnit.DAYS))
                .status(OrderStatus.LIVREE)
                .totalAmount(BigDecimal.ZERO)
                .build();

        BigDecimal total = BigDecimal.ZERO;
        for (Game game : List.of(catane, pandemic, azul)) {
            OrderLine line = OrderLine.builder()
                    .gameId(game.getId())
                    .gameName(game.getName())
                    .unitPrice(game.getPrice())
                    .quantity(1)
                    .build();
            order.addLine(line);
            total = total.add(line.getLineTotal());
        }
        order.setTotalAmount(total);
        orderRepository.save(order);

        reviewRepository.saveAll(List.of(
                Review.builder()
                        .game(catane).user(buyer).rating(5)
                        .comment("Un classique indémodable, parfait pour recevoir en famille !")
                        .createdAt(Instant.now().minus(4, ChronoUnit.DAYS))
                        .build(),
                Review.builder()
                        .game(pandemic).user(buyer).rating(4)
                        .comment("Très bon jeu coopératif, tendu jusqu'à la dernière carte.")
                        .createdAt(Instant.now().minus(3, ChronoUnit.DAYS))
                        .build(),
                Review.builder()
                        .game(azul).user(buyer).rating(5)
                        .comment("Magnifique et addictif, on ne s'en lasse pas.")
                        .createdAt(Instant.now().minus(2, ChronoUnit.DAYS))
                        .build()
        ));

        for (Game game : List.of(catane, pandemic, azul)) {
            List<Review> gameReviews = reviewRepository.findByGame_IdOrderByCreatedAtDesc(game.getId());
            double average = gameReviews.stream().mapToInt(Review::getRating).average().orElse(0);
            game.setReviewsAverage(average);
            game.setReviewsCount(gameReviews.size());
            gameRepository.save(game);
        }
    }

    private Game findByName(List<Game> games, String name) {
        return games.stream()
                .filter(game -> game.getName().equals(name))
                .findFirst()
                .orElseThrow(() -> new IllegalStateException("Jeu introuvable dans le seed : " + name));
    }
}
